### ISSUE TITLE
Question about the Turn Off Monitor widget

### ISSUE THREAD

**Issue by Bunkbed1510** [pic16f877ccs/Monitor-Off-Plasmoid#3]
Hello.

I've been using your Turn Off Monitor widget for KDE for over a year now and it's great. Thanks for your work! But 2 questions arose:

1. Is your widget compatible with a future release of KDE 6?

2. Is it possible to install your widget on a PC **without** the Internet? If so, what files are enough to download?

I would appreciate your answers. Thank you!

**Comment by pic16f877ccs** [comment]
Hello,

Thank you for your kind words and for using the Turn Off Monitor widget for KDE! I'm glad to hear that you find it useful.

As far as I know the widget is not compatible with KDE 6.

Installing the widget without the Internet: Yes, it is possible to install the widget on a PC without an internet connection. You can manually download the widget files from a device with internet access and then transfer them to your offline PC in the "~/.local/share/plasma/plasmoids/" folder.

I hope this helps! If you have further questions or need more assistance, please let me know.
